import { useState, useRef } from "react";
import { useNavigate } from "react-router";
import { validateTripImportData, importTripFromAI } from "@/services/trip-exchange-service";
import { ErrorNote, SectionCard, SectionNote } from "../parts";

export function AiTripSection() {
  const navigate = useNavigate();
  const [importing, setImporting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<{
    tripId: string;
    itemsCreated: number;
    itemsMatched: number;
    itemsMissingBarcode: number;
  } | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  function handleFileSelect(e: React.ChangeEvent<HTMLInputElement>) {
    setError(null);
    setResult(null);
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (event) => {
      const text = event.target?.result as string;
      try {
        const parsed = JSON.parse(text);
        const validation = validateTripImportData(parsed);
        if (!validation.valid) {
          setError(`Invalid file: ${validation.errors.join(", ")}`);
          return;
        }
        setImporting(true);
        try {
          setResult(await importTripFromAI(text));
        } catch (err) {
          setError(err instanceof Error ? err.message : "Trip import failed");
        } finally {
          setImporting(false);
          if (fileRef.current) fileRef.current.value = "";
        }
      } catch {
        setError("Could not parse file. Make sure it is valid JSON.");
      }
    };
    reader.readAsText(file);
  }

  return (
    <SectionCard title="Import Trip from AI">
      <SectionNote>
        Import a trip JSON generated by AI (from an &quot;Export for AI&quot; + receipt workflow).
        This creates a new completed trip with all items.
      </SectionNote>
      <label
        className={`block w-full rounded-lg border border-dashed border-purple-300 dark:border-purple-600 text-purple-600 dark:text-purple-400 px-4 py-2.5 text-sm font-medium hover:bg-purple-50 dark:hover:bg-purple-900/30 active:bg-purple-100 transition-colors cursor-pointer text-center ${importing ? "opacity-50 pointer-events-none" : ""}`}
      >
        {importing ? "Importing..." : "Import AI Trip JSON"}
        <input
          ref={fileRef}
          type="file"
          accept=".json"
          onChange={handleFileSelect}
          disabled={importing}
          className="hidden"
        />
      </label>
      {error && <ErrorNote>{error}</ErrorNote>}
      {result && (
        <div className="text-sm text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/30 rounded-lg p-3 space-y-2">
          <p className="font-medium">Trip imported successfully!</p>
          <ul className="text-xs space-y-1">
            <li>{result.itemsCreated} items created</li>
            {result.itemsMatched > 0 && <li>{result.itemsMatched} items matched to existing</li>}
            {result.itemsMissingBarcode > 0 && (
              <li className="text-purple-600 dark:text-purple-400">
                {result.itemsMissingBarcode} items need barcodes
              </li>
            )}
          </ul>
          <button
            type="button"
            onClick={() => navigate(`/trips/${result.tripId}`)}
            className="mt-2 w-full rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 cursor-pointer"
          >
            View Imported Trip
          </button>
        </div>
      )}
    </SectionCard>
  );
}
