import type { CreateItemInput } from "../contracts/types";

export const pluSeedData: CreateItemInput[] = [
  // ── Fruits ──────────────────────────────────────────
  { barcode: "4011", name: "Bananas", currentPrice: 0.23, unitType: "each", category: "Fruits" },
  { barcode: "4012", name: "Orange, Navel", currentPrice: 0.79, unitType: "each", category: "Fruits" },
  { barcode: "4017", name: "Apricots", currentPrice: 3.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4020", name: "Apple, Golden Delicious", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4021", name: "Apple, Gala", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4029", name: "Apple, Fuji", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4046", name: "Avocado, Hass (small)", currentPrice: 0.99, unitType: "each", category: "Fruits" },
  { barcode: "4048", name: "Lime", currentPrice: 0.25, unitType: "each", category: "Fruits" },
  { barcode: "4053", name: "Lemon", currentPrice: 0.35, unitType: "each", category: "Fruits" },
  { barcode: "4060", name: "Mango", currentPrice: 0.99, unitType: "each", category: "Fruits" },
  { barcode: "4065", name: "Grapes, Green Seedless", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4076", name: "Grapefruit, Ruby Red", currentPrice: 0.99, unitType: "each", category: "Fruits" },
  { barcode: "4078", name: "Nectarine", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4081", name: "Peach, Yellow", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "4101", name: "Pear, Bartlett", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4133", name: "Apple, Granny Smith", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4139", name: "Apple, Braeburn", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4152", name: "Apple, Pink Lady", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "4173", name: "Tangerine / Mandarin", currentPrice: 0.50, unitType: "each", category: "Fruits" },
  { barcode: "4225", name: "Avocado, Hass (large)", currentPrice: 1.49, unitType: "each", category: "Fruits" },
  { barcode: "4234", name: "Kiwi", currentPrice: 0.50, unitType: "each", category: "Fruits" },
  { barcode: "4236", name: "Cantaloupe", currentPrice: 2.99, unitType: "each", category: "Fruits" },
  { barcode: "4256", name: "Pineapple", currentPrice: 2.49, unitType: "each", category: "Fruits" },
  { barcode: "4299", name: "Pomegranate", currentPrice: 2.49, unitType: "each", category: "Fruits" },
  { barcode: "3283", name: "Honeydew Melon", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "4031", name: "Watermelon, Seedless (mini)", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "4395", name: "Blueberries", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "4399", name: "Strawberries", currentPrice: 3.99, unitType: "each", category: "Fruits" },
  { barcode: "3127", name: "Raspberries", currentPrice: 3.99, unitType: "each", category: "Fruits" },
  { barcode: "3355", name: "Blackberries", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "4247", name: "Plum, Black", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "4022", name: "Apple, Red Delicious", currentPrice: 1.79, unitType: "per_lb", category: "Fruits" },
  { barcode: "4038", name: "Apple, Honeycrisp", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "3082", name: "Cherries, Dark Sweet", currentPrice: 5.99, unitType: "per_lb", category: "Fruits" },

  // ── Vegetables ──────────────────────────────────────
  { barcode: "4062", name: "Cucumber", currentPrice: 0.99, unitType: "each", category: "Vegetables" },
  { barcode: "4664", name: "Tomato, Vine Ripe", currentPrice: 2.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4087", name: "Tomato, Roma", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4068", name: "Pepper, Green Bell", currentPrice: 0.79, unitType: "each", category: "Vegetables" },
  { barcode: "4069", name: "Pepper, Red Bell", currentPrice: 1.29, unitType: "each", category: "Vegetables" },
  { barcode: "4070", name: "Celery", currentPrice: 1.99, unitType: "each", category: "Vegetables" },
  { barcode: "4548", name: "Broccoli Crown", currentPrice: 1.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4073", name: "Corn, Sweet", currentPrice: 0.50, unitType: "each", category: "Vegetables" },
  { barcode: "4079", name: "Cauliflower", currentPrice: 2.99, unitType: "each", category: "Vegetables" },
  { barcode: "4080", name: "Asparagus", currentPrice: 3.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4082", name: "Mushrooms, White", currentPrice: 2.49, unitType: "each", category: "Vegetables" },
  { barcode: "4086", name: "Zucchini", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4085", name: "Eggplant", currentPrice: 1.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4061", name: "Lettuce, Iceberg", currentPrice: 1.49, unitType: "each", category: "Vegetables" },
  { barcode: "4627", name: "Brussels Sprouts", currentPrice: 2.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4091", name: "Kale, Green", currentPrice: 1.49, unitType: "each", category: "Vegetables" },
  { barcode: "4074", name: "Sweet Potato", currentPrice: 1.29, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4093", name: "Garlic", currentPrice: 0.50, unitType: "each", category: "Vegetables" },
  { barcode: "4094", name: "Onion, Yellow", currentPrice: 0.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4525", name: "Potato, Russet", currentPrice: 0.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4531", name: "Onion, Red", currentPrice: 1.29, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4663", name: "Onion, White", currentPrice: 1.29, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4578", name: "Potato, Red", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4608", name: "Carrots, Bunch", currentPrice: 1.49, unitType: "each", category: "Vegetables" },
  { barcode: "4677", name: "Spinach, Bunch", currentPrice: 1.99, unitType: "each", category: "Vegetables" },
  { barcode: "4688", name: "Cabbage, Green", currentPrice: 0.79, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4901", name: "Cilantro", currentPrice: 0.79, unitType: "each", category: "Vegetables" },
  { barcode: "4899", name: "Parsley, Italian Flat", currentPrice: 0.99, unitType: "each", category: "Vegetables" },
  { barcode: "4628", name: "Green Beans", currentPrice: 2.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4584", name: "Lettuce, Romaine", currentPrice: 1.69, unitType: "each", category: "Vegetables" },
  { barcode: "4536", name: "Pepper, Jalapeno", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4083", name: "Ginger Root", currentPrice: 3.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4759", name: "Tomato, Cherry (loose)", currentPrice: 3.99, unitType: "per_lb", category: "Vegetables" },

  // ── Organic Fruits (9-prefix PLU) ─────────────────
  { barcode: "94011", name: "Organic Bananas", currentPrice: 0.29, unitType: "each", category: "Fruits" },
  { barcode: "94012", name: "Organic Orange, Navel", currentPrice: 0.99, unitType: "each", category: "Fruits" },
  { barcode: "94017", name: "Organic Apricots", currentPrice: 4.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "94020", name: "Organic Apple, Golden Delicious", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "94021", name: "Organic Apple, Gala", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "94029", name: "Organic Apple, Fuji", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "94046", name: "Organic Avocado, Hass (small)", currentPrice: 1.29, unitType: "each", category: "Fruits" },
  { barcode: "94048", name: "Organic Lime", currentPrice: 0.35, unitType: "each", category: "Fruits" },
  { barcode: "94053", name: "Organic Lemon", currentPrice: 0.49, unitType: "each", category: "Fruits" },
  { barcode: "94060", name: "Organic Mango", currentPrice: 1.29, unitType: "each", category: "Fruits" },
  { barcode: "94065", name: "Organic Grapes, Green Seedless", currentPrice: 3.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "94076", name: "Organic Grapefruit, Ruby Red", currentPrice: 1.29, unitType: "each", category: "Fruits" },
  { barcode: "94078", name: "Organic Nectarine", currentPrice: 3.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "94081", name: "Organic Peach, Yellow", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "94101", name: "Organic Pear, Bartlett", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "94133", name: "Organic Apple, Granny Smith", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "94152", name: "Organic Apple, Pink Lady", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "94173", name: "Organic Tangerine / Mandarin", currentPrice: 0.69, unitType: "each", category: "Fruits" },
  { barcode: "94225", name: "Organic Avocado, Hass (large)", currentPrice: 1.99, unitType: "each", category: "Fruits" },
  { barcode: "94234", name: "Organic Kiwi", currentPrice: 0.69, unitType: "each", category: "Fruits" },
  { barcode: "94236", name: "Organic Cantaloupe", currentPrice: 3.99, unitType: "each", category: "Fruits" },
  { barcode: "94256", name: "Organic Pineapple", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "94031", name: "Organic Watermelon, Seedless (mini)", currentPrice: 4.49, unitType: "each", category: "Fruits" },
  { barcode: "94395", name: "Organic Blueberries", currentPrice: 4.49, unitType: "each", category: "Fruits" },
  { barcode: "94399", name: "Organic Strawberries", currentPrice: 4.49, unitType: "each", category: "Fruits" },
  { barcode: "93127", name: "Organic Raspberries", currentPrice: 4.49, unitType: "each", category: "Fruits" },
  { barcode: "93355", name: "Organic Blackberries", currentPrice: 3.99, unitType: "each", category: "Fruits" },
  { barcode: "94247", name: "Organic Plum, Black", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "94038", name: "Organic Apple, Honeycrisp", currentPrice: 3.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "93082", name: "Organic Cherries, Dark Sweet", currentPrice: 6.99, unitType: "per_lb", category: "Fruits" },

  // ── Organic Vegetables (9-prefix PLU) ─────────────
  { barcode: "94062", name: "Organic Cucumber", currentPrice: 1.29, unitType: "each", category: "Vegetables" },
  { barcode: "94664", name: "Organic Tomato, Vine Ripe", currentPrice: 2.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94087", name: "Organic Tomato, Roma", currentPrice: 1.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94068", name: "Organic Pepper, Green Bell", currentPrice: 1.29, unitType: "each", category: "Vegetables" },
  { barcode: "94069", name: "Organic Pepper, Red Bell", currentPrice: 1.79, unitType: "each", category: "Vegetables" },
  { barcode: "94070", name: "Organic Celery", currentPrice: 2.49, unitType: "each", category: "Vegetables" },
  { barcode: "94548", name: "Organic Broccoli Crown", currentPrice: 2.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94079", name: "Organic Cauliflower", currentPrice: 3.49, unitType: "each", category: "Vegetables" },
  { barcode: "94080", name: "Organic Asparagus", currentPrice: 3.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94086", name: "Organic Zucchini", currentPrice: 1.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94061", name: "Organic Lettuce, Iceberg", currentPrice: 1.99, unitType: "each", category: "Vegetables" },
  { barcode: "94627", name: "Organic Brussels Sprouts", currentPrice: 3.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94091", name: "Organic Kale, Green", currentPrice: 1.99, unitType: "each", category: "Vegetables" },
  { barcode: "94074", name: "Organic Sweet Potato", currentPrice: 1.79, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94093", name: "Organic Garlic", currentPrice: 0.79, unitType: "each", category: "Vegetables" },
  { barcode: "94094", name: "Organic Onion, Yellow", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94525", name: "Organic Potato, Russet", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94608", name: "Organic Carrots, Bunch", currentPrice: 1.99, unitType: "each", category: "Vegetables" },
  { barcode: "94677", name: "Organic Spinach, Bunch", currentPrice: 2.49, unitType: "each", category: "Vegetables" },
  { barcode: "94688", name: "Organic Cabbage, Green", currentPrice: 1.29, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94901", name: "Organic Cilantro", currentPrice: 0.99, unitType: "each", category: "Vegetables" },
  { barcode: "94899", name: "Organic Parsley, Italian Flat", currentPrice: 1.29, unitType: "each", category: "Vegetables" },
  { barcode: "94628", name: "Organic Green Beans", currentPrice: 2.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94584", name: "Organic Lettuce, Romaine", currentPrice: 1.99, unitType: "each", category: "Vegetables" },
  { barcode: "94083", name: "Organic Ginger Root", currentPrice: 4.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "94759", name: "Organic Tomato, Cherry (loose)", currentPrice: 4.99, unitType: "per_lb", category: "Vegetables" },
];
