import type { CreateItemInput } from "../contracts/types";

export const pluSeedData: CreateItemInput[] = [
  // ── Fruits ──────────────────────────────────────────
  { barcode: "4011", name: "Bananas", currentPrice: 0.23, unitType: "each", category: "Fruits" },
  { barcode: "4012", name: "Orange, Navel", currentPrice: 0.79, unitType: "each", category: "Fruits" },
  { barcode: "4017", name: "Apricots", currentPrice: 3.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4020", name: "Apple, Golden Delicious", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4021", name: "Apple, Gala", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4029", name: "Apple, Fuji", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4046", name: "Avocado, Hass (small)", currentPrice: 0.99, unitType: "each", category: "Fruits" },
  { barcode: "4048", name: "Lime", currentPrice: 0.25, unitType: "each", category: "Fruits" },
  { barcode: "4053", name: "Lemon", currentPrice: 0.35, unitType: "each", category: "Fruits" },
  { barcode: "4060", name: "Mango", currentPrice: 0.99, unitType: "each", category: "Fruits" },
  { barcode: "4065", name: "Grapes, Green Seedless", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4076", name: "Grapefruit, Ruby Red", currentPrice: 0.99, unitType: "each", category: "Fruits" },
  { barcode: "4078", name: "Nectarine", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4081", name: "Peach, Yellow", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "4101", name: "Pear, Bartlett", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4133", name: "Apple, Granny Smith", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4139", name: "Apple, Braeburn", currentPrice: 1.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "4152", name: "Apple, Pink Lady", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "4173", name: "Tangerine / Mandarin", currentPrice: 0.50, unitType: "each", category: "Fruits" },
  { barcode: "4225", name: "Avocado, Hass (large)", currentPrice: 1.49, unitType: "each", category: "Fruits" },
  { barcode: "4234", name: "Kiwi", currentPrice: 0.50, unitType: "each", category: "Fruits" },
  { barcode: "4236", name: "Cantaloupe", currentPrice: 2.99, unitType: "each", category: "Fruits" },
  { barcode: "4256", name: "Pineapple", currentPrice: 2.49, unitType: "each", category: "Fruits" },
  { barcode: "4299", name: "Pomegranate", currentPrice: 2.49, unitType: "each", category: "Fruits" },
  { barcode: "3283", name: "Honeydew Melon", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "4031", name: "Watermelon, Seedless (mini)", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "4395", name: "Blueberries", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "4399", name: "Strawberries", currentPrice: 3.99, unitType: "each", category: "Fruits" },
  { barcode: "3127", name: "Raspberries", currentPrice: 3.99, unitType: "each", category: "Fruits" },
  { barcode: "3355", name: "Blackberries", currentPrice: 3.49, unitType: "each", category: "Fruits" },
  { barcode: "4247", name: "Plum, Black", currentPrice: 2.49, unitType: "per_lb", category: "Fruits" },
  { barcode: "4022", name: "Apple, Red Delicious", currentPrice: 1.79, unitType: "per_lb", category: "Fruits" },
  { barcode: "4038", name: "Apple, Honeycrisp", currentPrice: 2.99, unitType: "per_lb", category: "Fruits" },
  { barcode: "3082", name: "Cherries, Dark Sweet", currentPrice: 5.99, unitType: "per_lb", category: "Fruits" },

  // ── Vegetables ──────────────────────────────────────
  { barcode: "4062", name: "Cucumber", currentPrice: 0.99, unitType: "each", category: "Vegetables" },
  { barcode: "4664", name: "Tomato, Vine Ripe", currentPrice: 2.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4087", name: "Tomato, Roma", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4068", name: "Pepper, Green Bell", currentPrice: 0.79, unitType: "each", category: "Vegetables" },
  { barcode: "4069", name: "Pepper, Red Bell", currentPrice: 1.29, unitType: "each", category: "Vegetables" },
  { barcode: "4070", name: "Celery", currentPrice: 1.99, unitType: "each", category: "Vegetables" },
  { barcode: "4548", name: "Broccoli Crown", currentPrice: 1.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4073", name: "Corn, Sweet", currentPrice: 0.50, unitType: "each", category: "Vegetables" },
  { barcode: "4079", name: "Cauliflower", currentPrice: 2.99, unitType: "each", category: "Vegetables" },
  { barcode: "4080", name: "Asparagus", currentPrice: 3.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4082", name: "Mushrooms, White", currentPrice: 2.49, unitType: "each", category: "Vegetables" },
  { barcode: "4086", name: "Zucchini", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4085", name: "Eggplant", currentPrice: 1.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4061", name: "Lettuce, Iceberg", currentPrice: 1.49, unitType: "each", category: "Vegetables" },
  { barcode: "4627", name: "Brussels Sprouts", currentPrice: 2.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4091", name: "Kale, Green", currentPrice: 1.49, unitType: "each", category: "Vegetables" },
  { barcode: "4074", name: "Sweet Potato", currentPrice: 1.29, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4093", name: "Garlic", currentPrice: 0.50, unitType: "each", category: "Vegetables" },
  { barcode: "4094", name: "Onion, Yellow", currentPrice: 0.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4525", name: "Potato, Russet", currentPrice: 0.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4531", name: "Onion, Red", currentPrice: 1.29, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4663", name: "Onion, White", currentPrice: 1.29, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4578", name: "Potato, Red", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4608", name: "Carrots, Bunch", currentPrice: 1.49, unitType: "each", category: "Vegetables" },
  { barcode: "4677", name: "Spinach, Bunch", currentPrice: 1.99, unitType: "each", category: "Vegetables" },
  { barcode: "4688", name: "Cabbage, Green", currentPrice: 0.79, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4901", name: "Cilantro", currentPrice: 0.79, unitType: "each", category: "Vegetables" },
  { barcode: "4899", name: "Parsley, Italian Flat", currentPrice: 0.99, unitType: "each", category: "Vegetables" },
  { barcode: "4628", name: "Green Beans", currentPrice: 2.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4584", name: "Lettuce, Romaine", currentPrice: 1.69, unitType: "each", category: "Vegetables" },
  { barcode: "4536", name: "Pepper, Jalapeno", currentPrice: 1.49, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4083", name: "Ginger Root", currentPrice: 3.99, unitType: "per_lb", category: "Vegetables" },
  { barcode: "4759", name: "Tomato, Cherry (loose)", currentPrice: 3.99, unitType: "per_lb", category: "Vegetables" },
];
