export const GROCERY_CATEGORIES = [
  "Bakery",
  "Beverages",
  "Breakfast & Cereal",
  "Canned Goods",
  "Condiments & Sauces",
  "Dairy & Eggs",
  "Deli",
  "Frozen Foods",
  "Grains, Pasta & Sides",
  "Health & Beauty",
  "Household & Cleaning",
  "International Foods",
  "Meat & Seafood",
  "Oils & Vinegars",
  "Paper & Plastic Goods",
  "Pet Supplies",
  "Produce",
  "Snacks & Candy",
  "Spices & Seasonings",
];
